#!/bin/sh
# Script extracts gettext strings from plugin files
# Copyright (c) 1999-2005 The SquirrelMail Project Team
# Licensed under the GNU GPL. For full terms see the file COPYING.
# $Id: xgetpot,v 1.1 2005/07/26 08:36:46 tokul Exp $
XGETTEXT_OPTIONS="--keyword=_ -keyword=N_ --default-domain=select_language --add-comments"

# Allows controlling language option
# (gettext v.0.10.40 = -C, gettext 0.11+ = -L php).
if [ $SM_LANG_PHP ] ; then
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -L php";
else
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -C";
fi

xgettext ${XGETTEXT_OPTIONS} \
    *.php --output=select_language.pot
